/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chickenSaleAccount;


import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abood
 */
public class passwordFram extends javax.swing.JFrame {
     private  int countprise=0;
     private  SimpleDateFormat simple =new SimpleDateFormat("dd-MM-YYYY");
     private cashFrame cash;
      private debtFrame debt;
      private addBills billt;
    public String pass = "em1919";
        public String passDebt = "em1919";
       
       public int thefun=0; 
boolean  count=false;
boolean  countDebt=false;
boolean countbillt=false;

    public passwordFram( int i) throws Exception {
        initComponents();
      cash=new cashFrame();
  debt= new debtFrame();
  billt=new addBills();
         thefun=i;     
    
    }


     @SuppressWarnings("empty-statement")
     
     
     
     private void openCaheFrame() throws Exception{
  
    
            if(!count){
       
  

            
      DefaultTableModel mode1 = (DefaultTableModel)cash.tableTotalSell.getModel();
              mainClass ac=new mainClass();
                 Date d1 = new Date(); 
                String allDate= simple.format(d1);
               String s[]=allDate.split("-");
              
               int day=Integer.parseInt(s[0]);
               int month=Integer.parseInt(s[1]);
               int yer=Integer.parseInt(s[2]);
               int i=1;
               for(;i<=day;i++){
           
              String d=Integer.toString(  ac.carh(i+"", s[1], s[2]));
                   String []b=new String[2];
                   b[1]=i+"-"+s[1]+"-"+s[2];
                   b[0]=d;
            mode1.addRow(b);
               }
             cash.setVisible(true);
             cash.setResizable(false);
             cash.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
             count=true;
            }
            else{
            cash.setVisible(true);
            cash.setResizable(false);
            cash.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }


}
 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bEnter = new javax.swing.JButton();
        fieldPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("كلمة السر");

        bEnter.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bEnter.setText("ادخال");
        bEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnterActionPerformed(evt);
            }
        });

        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(fieldPassword))
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(bEnter)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doaction(){
        try {
           
           if(fieldPassword.getText().equals("em1919")){
    this.setVisible(false);
     this.fieldPassword.setText("");
      cash.setVisible(true); 
      DefaultTableModel mode1 = (DefaultTableModel)cash.tableTotalSell.getModel();
              mainClass ac=new mainClass();
              mode1.getDataVector().removeAllElements();
    revalidate();

                 Date d1 = new Date(); 
                String allDate= simple.format(d1);
               String s[]=allDate.split("-");
              
               int day=Integer.parseInt(s[0]);
               int month=Integer.parseInt(s[1]);
               int yer=Integer.parseInt(s[2]);
               int i=1;
               for(;i<=day;i++){
           if(i<10){
              String d=Integer.toString(  ac.carh("0"+i, s[1], s[2]));
                   String []b=new String[2];
                   b[1]=i+"-"+s[1]+"-"+s[2];
                   b[0]=d;
     mode1.addRow(b);
     
           }
           else{
           
             String d=Integer.toString(  ac.carh(i+"", s[1], s[2]));
                   String []b=new String[2];
                   b[1]=i+"-"+s[1]+"-"+s[2];
                   b[0]=d;
     mode1.addRow(b);
           
           
           }
               }
             cash.setVisible(true);
             cash.setResizable(false);
             cash.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
             
            

}
else{
    JOptionPane.showMessageDialog(this,"كلمة السر غير صحيحة");
     fieldPassword.setText("");
}
         
           
         } catch (Exception ex) {
             Logger.getLogger(passwordFram.class.getName()).log(Level.SEVERE, null, ex);
         }
 
    
    }
    private void doactionDebt(){
 if(fieldPassword.getText().equals("em1919")){
    this.setVisible(false);
     this.fieldPassword.setText("");
    
   if(!countDebt){
      
             debt.setVisible(true);
              debt.setResizable(false);
              debt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
             countDebt=true;
            }
   else {
             debt.setVisible(true);
             debt.setResizable(false);
             debt .setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }

    


 }
 else{
 JOptionPane.showMessageDialog(this,"كلمة السر غير صحيحة");
 fieldPassword.setText("");
 }
    }
    private void doactionBillts(){
    if(fieldPassword.getText().equals("em1919")){
    this.setVisible(false);
     this.fieldPassword.setText("");
    
   if(!countbillt){
      
             billt.setVisible(true);
              billt.setResizable(false);
              billt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
             countbillt=true;
            }
   else {
             billt.setVisible(true);
             billt.setResizable(false);
             billt .setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }

    


 }
 else{
 JOptionPane.showMessageDialog(this,"كلمة السر غير صحيحة");
 fieldPassword.setText("");
    
    
    }
    }
    
    private void bEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnterActionPerformed

         if(thefun==0)
this.doaction();
         else if(thefun==1)
 this.doactionDebt();
         else 
             this.doactionBillts();
             

    }//GEN-LAST:event_bEnterActionPerformed

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
            if(thefun==0)
this.doaction();
     else if(thefun==1)
 this.doactionDebt();
         else 
             this.doactionBillts();
             

        
    }//GEN-LAST:event_fieldPasswordActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   /*     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new passwordFram(thefun).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(passwordFram.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });*/
    }
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnter;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
